function output = read_specs(filename)
file_text = fileread(filename);
file_lines = splitlines(file_text);

structure = struct(...
    "baud_rate",            file_lines(3), ...
    "com_port",             file_lines(5), ...
    "grid_size",            file_lines(7), ...
    "modules_x",            file_lines(9), ...
    "modules_y",            file_lines(11), ...
    "sigma",                file_lines(13), ...
    "kernel",               file_lines(15));

structure.baud_rate              = str2num(structure.baud_rate);
structure.grid_size              = str2num(structure.grid_size);
structure.modules_x              = str2num(structure.modules_x);
structure.modules_y              = str2num(structure.modules_y);
structure.sigma                  = str2num(structure.sigma);
structure.kernel                 = str2num(structure.kernel);

output = structure;
end
